version: "3.7"

services:
  web:
    build: ./personal-site
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./personal-site:/opt/services/personal-site
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=aaroncymor
      - POSTGRES_PASSWORD=aaroncymor
      - POSTGRES_DB=personalsitedb

volumes:
  postgres_data:
